name: Build and publish release

on:
  push:
    tags:
      - "*"
  
  workflow_dispatch:

jobs:
  
  build:
    name: build and upload artifacts
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
      
      - name: Restore Packages
        run: nuget restore IMS_Enterprise_ECMA.sln

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=ID::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Build Solution
        run: |
          msbuild.exe IMS_Enterprise_ECMA.sln -property:platform="Any CPU" -property:Configuration="Release"
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: vigobas-ims-enterprise-ma
          path: bin/release/IMS_Enterprise_ECMA.dll
  publish:
    needs: build
    name: publish artifacts to github release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: vigobas-ims-enterprise-ma
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: IMS_Enterprise_ECMA.dll
